name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: rpareixx/esphome_hydrophonictower/.github/workflows/publish.yml@main
    with:
      files: mfivestickhydrophonictower.yaml
      name: esphome-hydrophonictower
